Repository Leaflet/Leaflet, pull requests merged in 2021-12, with the labels that each got.

#7812 Create leaflet-coloricon.md
  docs/_plugins/markers-renderers/leaflet-coloricon.md
Labels: plugins

#7335 makes L.Browser mutable
  src/core/Browser.js
  src/core/index.js
  src/dom/DomEvent.Pointer.js
  src/dom/DomEvent.js
  src/dom/DomUtil.js
  src/dom/Draggable.js
  src/layer/marker/Icon.js
  src/layer/tile/GridLayer.js
  src/layer/tile/TileLayer.WMS.js
  src/layer/tile/TileLayer.js
  src/layer/vector/Canvas.js
  src/layer/vector/Renderer.js
  src/layer/vector/SVG.Util.js
  src/layer/vector/SVG.js
  src/map/Map.js
  src/map/handler/Map.TapHold.js
  src/map/handler/Map.TouchZoom.js
Labels: tests

#7633 bindTooltip should unbind existent tooltip
  spec/suites/layer/TooltipSpec.js
  src/layer/Tooltip.js
Labels: bug

#7813 Locate - locationfound: Add check if map container has leaflet_id / is existing
  spec/suites/map/MapSpec.js
  src/map/Map.js
Labels: bug

#7609 Correct condition to add zoom limits for Layer
  src/layer/Layer.js
Labels: bug

#7563 Fix Bug: permanent & sticky tooltip
  spec/suites/layer/TooltipSpec.js
  src/layer/Tooltip.js
Labels: bug

#7459 Break the reference to the options of the Class prototype
  spec/suites/core/ClassSpec.js
  src/core/Class.js
Labels: bug

#7832 leaflet.zoomfs compatibility
  docs/_plugins/fullscreen-controls/leaflet-zoomfs.md
Labels: plugins

#7833 add demo url for the plugin
  docs/_plugins/fullscreen-controls/leaflet-fullscreen.md
Labels: plugins

#7092 Better icon image path detection
  dist/leaflet.css
  spec/suites/layer/marker/Icon.DefaultSpec.js
  src/layer/marker/Icon.Default.js
Labels: compatibility

#7853 Upload files to AWS even if the file-size is the same
  .github/workflows/main.yml
Labels: bug

#7845 Added missing tests to index.html
  spec/index.html
  spec/suites/core/GeneralSpec.js
  spec/suites/geo/crs/CRSSpec.js
  spec/suites/geo/projection/ProjectionSpec.js
Labels: tests

#7850 Set `role=button` on the Layer control
  src/control/Control.Layers.js
Labels: accessibility

#7854 Publish package to NPM when pushing tag
  .github/workflows/main.yml
  RELEASE.md
  package.json
Labels: feature

#7778 Update the doc of DivOverlay
  src/layer/DivOverlay.js
  src/layer/Popup.js
Labels: docs
