Repository Leaflet/Leaflet, pull requests merged in 2022-06, with the labels that each got.

#8285 Plugin "minimap/WorldMiniMap"
  docs/_plugins/minimaps-synced-maps/leaflet-WorldMiniMap.md
Labels: plugins

#7882 Extend Bounds to have the same functions as LatLngBounds
  spec/suites/geometry/BoundsSpec.js
  src/geometry/Bounds.js
Labels: feature

#8296 website: ensure no borders on dialog iframe
  docs/docs/css/main.css
Labels: bug

#8299 Add pre-commit linting to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs, workflow
