Repository Leaflet/Leaflet, pull requests merged in 2022-08, with the labels that each got.

#8384 Add test for containerPointToLatLng and latLngToContainerPoint methods
  spec/suites/map/MapSpec.js
Labels: tests

#8298 Fix 2 step mouse wheel scrolling
  src/core/Browser.js
  src/dom/DomEvent.js
Labels: bug, ux

#8390 Implemented test for panTo method of Map
  spec/suites/map/MapSpec.js
Labels: tests

#7783 Add content and latlng while initializing of Popup / Tooltip
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  src/layer/DivOverlay.js
  src/layer/Popup.js
  src/layer/Tooltip.js
Labels: feature

#7637 Fix invalid GeoJSON returned
  spec/suites/layer/GeoJSONSpec.js
  src/layer/GeoJSON.js
Labels: bug
