Repository Leaflet/Leaflet, pull requests merged in 2022-10, with the labels that each got.

#8501 Remove char which causes error in YAML while serving
  docs/_plugins/dataviz/leaflet-l7.md
Labels: plugins

#8500 Remove `maxMargin` from `Bounds.equals` doc string
  src/geometry/Bounds.js
Labels: docs

#8499 Update tests `index.html` and add missing RectangleSpec
  spec/index.html
Labels: tests

#8505 test: add test for map stopLocate (#8371)
  spec/suites/map/MapSpec.js
Labels: tests

#8503 Added test cases for Map:addHandler method
  spec/suites/map/MapSpec.js
Labels: tests

#8406 Fix: added test cases for Map:mouseEventToContainerPoint method.
  spec/suites/map/MapSpec.js
Labels: tests

#8424 Cover Map Locate with Unit Tests
  spec/suites/map/MapSpec.js
Labels: tests

#8504 Add build-docs job to main github actions file
  .github/workflows/main.yml
  .gitignore
  docs/_config.yml
Labels: workflow

#8517 chore: replaced `substr` with `substring`
  docs/docs/js/reference.js
  docs/edit.html
Labels: refactoring

#8512 Add `getWheelPxFactor` and fix test `changes the option 'wheelPxPerZoomLevel'` for mac
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
  src/dom/DomEvent.js
Labels: api, tests

#8518 Speed up PathSpec's "Add layer inside move handler" test: 611ms to 5ms (122x faster)
  spec/suites/layer/vector/PathSpec.js
Labels: tests

#8519 Speed up tests Map.ScrollWheelZoomSpec and Map.DoubleClickZoomSpec
  spec/suites/map/handler/Map.DoubleClickZoomSpec.js
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
Labels: tests

#8494 Add step for release assets
  RELEASE.md
Labels: workflow

#8526 Update changelog for release of v1.9.2
  CHANGELOG.md
Labels: workflow

#8527 Update documentation for v1.9.2
  docs/_config.yml
  docs/_posts/2022-09-21-leaflet-1.9.0.md
  docs/download.md
  docs/reference.html
Labels: docs, workflow

#8528 Update changelog with latest revisions
  CHANGELOG.md
Labels: workflow

#8516 Add Dependabot config for Bundler dependencies
  .github/dependabot.yml
  .github/workflows/main.yml
  .gitignore
  CONTRIBUTING.md
  docs/.gitignore
  docs/.ruby-version
  docs/Gemfile
  docs/Gemfile.lock
Labels: workflow

#7912 Change `<section>` to `<fieldset>` in the layers control
  dist/leaflet.css
  src/control/Control.Layers.js
Labels: feature, accessibility, breaking

#8542 Fix 2 links without URLs in docs
  docs/examples/extending/extending-2-layers.md
  src/dom/DomUtil.js
Labels: bug, docs

#8420 closes #8366: panBy() test
  spec/suites/map/MapSpec.js
Labels: tests

#8520 Alternate fix for PopUp keepInView recursion and speed up associated test
  debug/map/popup-keepinview.html
  spec/suites/layer/PopupSpec.js
  src/layer/Popup.js
Labels: tests

#8544 Speed up tests relating to containerPoint / layerPoint methods
  spec/suites/map/MapSpec.js
Labels: tests

#8545 Speed up tests relating to focusing on Marker
  spec/suites/layer/marker/MarkerSpec.js
Labels: tests

#8546 Speed up TileLayer.setUrl test (251ms to 13ms)
  spec/suites/layer/tile/TileLayerSpec.js
Labels: tests

#8540 tests workflow for mac and win
  .github/workflows/main.yml
  package-lock.json
  package.json
  spec/karma.conf.js
Labels: tests

#8550 Support sticky maps
  src/map/Map.js
Labels: feature

#8547 Align the scale control's alpha transparency with the attribution control
  dist/leaflet.css
Labels: accessibility

#8548 Allow the scale control's text to overflow the container
  dist/leaflet.css
Labels: accessibility

#8555 Create Leaflet.fullscreen plugin
  docs/_plugins/fullscreen-controls/leaflet.fullscreen
Labels: plugins

#8559 Remove Internet Explorer from browser detection
  debug/vector/geojson.html
  dist/leaflet.css
  docs/examples/choropleth/example.md
  docs/examples/choropleth/index.md
  spec/suites/dom/DomUtilSpec.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/marker/Marker.DragSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/map/handler/Map.DragSpec.js
  src/core/Browser.js
  src/dom/DomUtil.js
  src/layer/tile/GridLayer.js
  src/map/Map.js
Labels: api, compatibility, breaking, ie

#8556 Expand layers control on Enter keydown
  spec/suites/control/Control.LayersSpec.js
  src/control/Control.Layers.js
Labels: accessibility

#8563 Split ESLint config and clean it up
  .eslintrc.js
  package.json
  spec/.eslintrc
  spec/.eslintrc.js
Labels: refactoring, workflow

#8571 Fixes event target of popupopen event and adds test
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  src/layer/Popup.js
  src/layer/Tooltip.js
Labels: bug

#8582 Upgrade Rollup to version 3
  build/banner.js
  build/rollup-config.js
  build/rollup-config.mjs
  package-lock.json
  package.json
Labels: dependencies, workflow

#8583 Upgrade ESLint config to latest version
  .eslintrc.js
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#8584 Enable `arrow-spacing` linting rule and fix issues
  .eslintrc.js
  docs/docs/js/docs.js
Labels: refactoring

#8585 Enable `func-name-matching` linting rule and fix issues
  .eslintrc.js
  src/map/handler/Map.TapHold.js
Labels: refactoring

#8586 Enable `no-duplicate-imports` linting rule and fix issues
  .eslintrc.js
  src/layer/GeoJSON.js
Labels: refactoring

#8581 test: add test for map `stop` (#8369)
  spec/suites/map/MapSpec.js
Labels: tests

#8587 Enable `prefer-template` linting rule and fix issues
  .eslintrc.js
  build/docs.js
  docs/docs/js/docs.js
  docs/docs/js/reference.js
  docs/examples/choropleth/example.md
  docs/examples/extending/kittenlayer.md
  docs/examples/extending/pixelorigin.md
  docs/examples/extending/tilt.md
  docs/examples/geojson/example.md
  docs/examples/mobile/example.md
  docs/examples/quick-start/example.md
  docs/examples/zoom-levels/example-delta.md
  docs/examples/zoom-levels/example-fractional.md
  docs/examples/zoom-levels/example-setzoom.md
  spec/suites/dom/DomUtilSpec.js
  spec/suites/geometry/PointSpec.js
  spec/suites/layer/GeoJSONSpec.js
  spec/suites/layer/ImageOverlaySpec.js
  spec/suites/layer/TooltipSpec.js
  spec/suites/layer/marker/Icon.DefaultSpec.js
  spec/suites/layer/marker/Marker.DragSpec.js
  spec/suites/layer/marker/MarkerSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.DragSpec.js
  src/control/Control.Attribution.js
  src/control/Control.Layers.js
  src/control/Control.Scale.js
  src/control/Control.Zoom.js
  src/control/Control.js
  src/core/Events.js
  src/core/Util.js
  src/dom/DomEvent.js
  src/dom/DomUtil.js
  src/geo/LatLng.js
  src/geometry/LineUtil.js
  src/geometry/Point.js
  src/layer/DivOverlay.js
  src/layer/GeoJSON.js
  src/layer/ImageOverlay.js
  src/layer/Popup.js
  src/layer/Tooltip.js
  src/layer/marker/DivIcon.js
  src/layer/marker/Icon.js
  src/layer/marker/Marker.js
  src/layer/tile/GridLayer.js
  src/layer/vector/Canvas.js
  src/layer/vector/SVG.Util.js
  src/layer/vector/SVG.js
  src/map/Map.js
  src/map/handler/Map.BoxZoom.js
Labels: refactoring

#8593 Enable `prefer-rest-params` linting rule and fix issues
  .eslintrc.js
  spec/suites/SpecHelper.js
  spec/suites/layer/tile/GridLayerSpec.js
  src/core/Class.js
  src/core/Util.js
  src/layer/LayerGroup.js
Labels: refactoring

#8600 Remove legacy CSS hacks and unused prefixes
  dist/leaflet.css
Labels: refactoring, compatibility, breaking

#8604 Remove Karma launcher for Microsoft Edge
  package-lock.json
  package.json
  spec/karma.conf.js
Labels: compatibility, tests, breaking

#8603 Remove Microsoft-specific Pointer Events from browser detection
  src/core/Browser.js
  src/dom/DomEvent.Pointer.js
Labels: api, compatibility, breaking, ie

#8607 Remove Android from browser detection
  src/core/Browser.js
Labels: android, api, compatibility, breaking

#8606 Remove Edge from browser detection
  docs/examples/choropleth/example.md
  docs/examples/choropleth/index.md
  src/core/Browser.js
  src/dom/DomEvent.js
Labels: api, compatibility, breaking

#8621 Remove Opera from browser detection
  docs/examples/choropleth/example.md
  docs/examples/choropleth/index.md
  src/core/Browser.js
  src/map/Map.js
Labels: api, compatibility, breaking

#8622 Remove PhantomJS from browser detection
  src/core/Browser.js
Labels: api, compatibility, breaking

#8623 Remove `indexOf()` function from Util
  spec/suites/SpecHelper.js
  spec/suites/layer/tile/TileLayerSpec.js
  src/control/Control.js
  src/core/Browser.js
  src/core/Util.js
  src/dom/DomEvent.js
  src/map/Map.js
Labels: refactoring, api, compatibility, breaking

#8614 Added leaflet.LayerGroup.Conditional to plugin list
  docs/_plugins/clustering-decluttering/leaflet-layergroup-conditional.md
Labels: plugins

#8610 Convert build scripts into ESM
  .eslintrc.js
  build/docs.mjs
  build/integrity.js
  build/integrity.mjs
  package.json
Labels: refactoring, workflow

#8612 Use ResizeObserver for map resizes
  spec/suites/map/MapSpec.js
  src/map/Map.js
Labels: refactoring, breaking

#8562 Fix worldCopyJump with Keyboard
  spec/suites/map/handler/Map.KeyboardSpec.js
  src/map/handler/Map.Keyboard.js
Labels: bug

#8627 Add a description of the Leaflet.inflatable-markers-group
  docs/_plugins/clustering-decluttering/leaflet-inflatable-markers-group.md
Labels: plugins

#8628 Fix CSS syntax error in leaflet.css
  dist/leaflet.css
Labels: bug

#8099 Create leaflet-polygon-fillPattern-canvas
  docs/_plugins/markers-renderers/leaflet-polygon-fillPattern-canvas.md
Labels: plugins

#8435 Adding tests for 'layerPointToLatLng' method #8375
  spec/suites/map/MapSpec.js
Labels: tests

#7344 Fix closed coord's reference in latLngsToCoords
  spec/suites/layer/GeoJSONSpec.js
  src/layer/GeoJSON.js
Labels: feature
