Repository Leaflet/Leaflet, pull requests merged in 2022-07, with the labels that each got.

#8317 Create leaflet-sidepanel.md
  docs/_plugins/user-interface/leaflet-sidepanel.md
Labels: plugins

#8331 Replace deprecated eslint-plugin-script-tags
  package-lock.json
  package.json
Labels: dependencies

#8340 Add test for '_containsPoint' method of CircleMarker
  spec/suites/layer/vector/CircleMarkerSpec.js
Labels: tests

#8339 Update leafletgeopackage.md
  docs/_plugins/overlay-data-formats/leafletgeopackage.md
Labels: plugins

#7603 Update `getCenter()` calculation and move it to PolyUtil / LineUtil
  spec/suites/geometry/LineUtilSpec.js
  spec/suites/geometry/PolyUtilSpec.js
  spec/suites/layer/vector/PolygonSpec.js
  spec/suites/layer/vector/PolylineSpec.js
  src/geometry/LineUtil.js
  src/geometry/PolyUtil.js
  src/layer/vector/Polygon.js
  src/layer/vector/Polyline.js
Labels: feature, bug

#8206 Additional Map Tests
  spec/suites/map/MapSpec.js
Labels: tests

#8329 Expose ESM entrypoint with Leaflet global
  build/rollup-config.js
  debug/tests/esm.html
  package.json
  spec/karma.conf.js
  src/LeafletWithGlobals.js
Labels: feature, compatibility

#8037 test: add coverage for Layer\_addZoomLimit
  spec/suites/map/MapSpec.js
Labels: tests, needs decision

#7780 Anchor links for headers & collapsed links
  docs/docs/js/reference.js
Labels: docs
