Repository Leaflet/Leaflet, pull requests merged in 2022-09, with the labels that each got.

#8433 Update Center calculation to work for very small layers too
  spec/suites/geometry/LineUtilSpec.js
  spec/suites/geometry/PolyUtilSpec.js
  src/geometry/LineUtil.js
  src/geometry/PolyUtil.js
  src/layer/vector/Polygon.js
  src/layer/vector/Polyline.js
Labels: blocker

#8446 Update changelog for v1.9.0
  CHANGELOG.md
Labels: workflow

#8196 Drop legacy VML code & official support for IE7–8
  dist/leaflet.css
  docs/index.html
  src/core/Browser.js
  src/layer/vector/SVG.Util.js
  src/layer/vector/SVG.VML.js
  src/layer/vector/SVG.js
Labels: breaking, ie

#8264 Remove Internet Explorer from test framework
  .github/workflows/main.yml
  package-lock.json
  package.json
  spec/karma.conf.js
Labels: compatibility, workflow, ie

#8453 Update website & docs for v1.9.0
  RELEASE.md
  docs/_config.yml
  docs/_posts/2022-09-21-leaflet-1.9.0.md
  docs/download.md
  docs/index.html
  docs/reference-1.8.0.html
  docs/reference-1.9.0.html
  docs/reference-versions.html
  docs/reference.html
Labels: docs

#8456 Fix the resource integrity hashes
  RELEASE.md
  docs/_config.yml
Labels: bug, docs

#8462 add leaflet.migration
  docs/_plugins/dataviz/leaflet-migration.md
Labels: plugins

#8466 Use the topmost browsing context for links in tutorial frames
  docs/_layouts/tutorial_frame.html
Labels: docs

#8468 README: update JS size for 1.9.1
  README.md
Labels: docs

#8469 Change leaflet-migration demo
  docs/_plugins/dataviz/leaflet-migration.md
Labels: plugins

#8463 Upgrade dependencies, including Sinon & Mocha
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#8475 Remove the release check to manually modify the version number in `reference.html`
  RELEASE.md
Labels: workflow

#8476 Update the Leaflet Editor's `description` and map `id`
  docs/edit.html
Labels: workflow

#8481 Fix test on mac `changes the option 'wheelPxPerZoomLevel'`
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
Labels: tests

#8480 Make test runner output cleaner
  spec/karma.conf.js
Labels: workflow

#8487 Use different cache keys
  .github/workflows/main.yml
Labels: workflow

#8484 Replace `Util.bind()` with `Function.bind()`
  spec/suites/core/UtilSpec.js
  spec/suites/layer/LayerGroupSpec.js
  spec/suites/map/MapSpec.js
  src/control/Control.Layers.js
  src/core/Util.js
  src/core/index.js
  src/layer/DivOverlay.js
  src/layer/ImageOverlay.js
  src/layer/VideoOverlay.js
  src/layer/tile/GridLayer.js
  src/layer/tile/TileLayer.js
  src/layer/vector/Canvas.js
  src/map/Map.js
  src/map/handler/Map.BoxZoom.js
  src/map/handler/Map.ScrollWheelZoom.js
  src/map/handler/Map.TapHold.js
  src/map/handler/Map.TouchZoom.js
Labels: refactoring, breaking

#8493 Drop ESM entrypoint from package
  build/rollup-config.js
  debug/tests/esm.html
  package.json
  spec/karma.conf.js
  src/LeafletWithGlobals.js
Labels: blocker, compatibility

#8429 added tests for panInsideBounds
  spec/suites/map/MapSpec.js
Labels: tests

#8415 Quick-start: fix link in code block.
  docs/examples/quick-start/index.md
Labels: bug, docs

#8403 Added testing for mouseEventLatLng
  spec/suites/map/MapSpec.js
Labels: tests
