Repository Leaflet/Leaflet, pull requests merged in 2022-03, with the labels that each got.

#8019 Add check for blocker issues/PRs in RELEASE.md
  RELEASE.md
Labels: workflow

#7996 Enable outlines on `leaflet-container` for keyboard users
  dist/leaflet.css
Labels: accessibility

#8047 Plugins guide accessibility section: add links to beginner-friendly documentation
  PLUGIN-GUIDE.md
Labels: docs, accessibility

#8049 Plugins: Add Leaflet.ImageOverlay.OGCAPI
  docs/_plugins/basemap-formats/leaflet-imageoverlay-ogcapi.md
Labels: plugins

#8046 Potentially fix path for tagged artifacts upload
  .github/workflows/main.yml
Labels: workflow

#8058 Fix SVG perf regression by partially bringing back will-change
  dist/leaflet.css
Labels: performance

#8057 Increase default font sizes for improved legibility
  dist/leaflet.css
Labels: ux, accessibility

#7852 Cleanup all tests
  spec/.eslintrc
  spec/index.html
  spec/suites/SpecHelper.js
  spec/suites/control/Control.AttributionSpec.js
  spec/suites/control/Control.LayersSpec.js
  spec/suites/control/ControlSpec.js
  spec/suites/geo/LatLngBoundsSpec.js
  spec/suites/geo/LatLngSpec.js
  spec/suites/geo/crs/CRSSpec.js
  spec/suites/geo/projection/ProjectionSpec.js
  spec/suites/geometry/BoundsSpec.js
  spec/suites/geometry/LineUtilSpec.js
  spec/suites/geometry/PointSpec.js
  spec/suites/geometry/PolyUtilSpec.js
  spec/suites/geometry/TransformationSpec.js
  spec/suites/layer/GeoJSONSpec.js
  spec/suites/layer/ImageOverlaySpec.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  spec/suites/layer/VideoOverlaySpec.js
  spec/suites/layer/marker/Icon.DefaultSpec.js
  spec/suites/layer/marker/Marker.DragSpec.js
  spec/suites/layer/marker/MarkerSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/layer/vector/CanvasSpec.js
  spec/suites/layer/vector/CircleMarkerSpec.js
  spec/suites/layer/vector/CircleSpec.js
  spec/suites/layer/vector/PathSpec.js
  spec/suites/layer/vector/PolygonSpec.js
  spec/suites/layer/vector/PolylineGeometrySpec.js
  spec/suites/layer/vector/PolylineSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.BoxZoom.js
  spec/suites/map/handler/Map.DragSpec.js
  spec/suites/map/handler/Map.KeyboardSpec.js
  spec/suites/map/handler/Map.TapHoldSpec.js
  spec/suites/map/handler/Map.TouchZoomSpec.js
Labels: tests

#8083 bugFix: moving scroll-padding-top prop to reference.css
  docs/SlavaUkraini/docs/css/main.css
  docs/SlavaUkraini/docs/css/reference.css
  docs/docs/css/main.css
  docs/docs/css/reference.css
Labels: bug, docs

#8081 New tutorial: Guidelines to basic Leaflet accessibility
  docs/SlavaUkraini/examples.md
  docs/SlavaUkraini/examples/accessibility/example.md
  docs/SlavaUkraini/examples/accessibility/index.md
  docs/SlavaUkraini/examples/accessibility/thumbnail.png
Labels: docs, accessibility

#8084 Fix undefined iconAnchor
  spec/suites/layer/marker/MarkerSpec.js
  src/layer/marker/Marker.js
Labels: blocker, bug

#8088 Cover `DomEvent` with unit tests
  spec/suites/dom/DomEventSpec.js
Labels: tests

#8091 Fix panFocus on icon with no iconSize
  spec/suites/layer/marker/MarkerSpec.js
  src/layer/marker/Marker.js
Labels: blocker

#8097 leaflet-radar
  docs/_plugins/overlay-animations/leaflet-radar.md
Labels: plugins

#8096 Plugins: Add leaflet-rotate
  docs/_plugins/tile-image-display/leaflet-rotate.md
Labels: plugins

#8102 Remove an old iOS hack to fix glitches on rapid zoom
  src/map/Map.js
Labels: blocker
