Repository Leaflet/Leaflet, pull requests merged in 2022-04, with the labels that each got.

#8105 Small typo in map dragging option description
  src/map/handler/Map.Drag.js
Labels: docs

#8103 Fix vector drift when dragging and immediately zooming
  spec/suites/map/handler/Map.TouchZoomSpec.js
  src/dom/Draggable.js
  src/layer/vector/Renderer.js
  src/layer/vector/SVG.js
  src/map/handler/Map.Drag.js
Labels: blocker

#8118 Add retries for flaky IE10 tests
  spec/suites/layer/tile/TileLayerSpec.js
Labels: tests

#8128 Changelog update (1.8.0-beta.0): document the change to fonts as breaking
  CHANGELOG.md
Labels: docs

#8067 Extend Layers Control tutorial to add layer dynamically
  docs/SlavaUkraini/examples/layers-control/example.md
  docs/SlavaUkraini/examples/layers-control/index.md
  docs/SlavaUkraini/examples/layers-control/thumbnail.png
Labels: docs

#8136 Popup should have a min-height
  dist/leaflet.css
Labels: ux

#7436 Add Array traitment into latLngToCoords/latLngsToCoords
  spec/suites/layer/GeoJSONSpec.js
  src/layer/GeoJSON.js
Labels: bug

#7547 DomUtil function tests
  spec/suites/dom/DomUtilSpec.js
Labels: tests

#8148 Fix missing plugins section: Synthetic Overlays
  docs/SlavaUkraini/plugins.md
Labels: bug, plugins

#8146 Link to the new markers guideline from docs
  src/layer/marker/Marker.js
Labels: docs

#7908 Small enhancement to the popup's close button
  dist/leaflet.css
Labels: ux, accessibility, needs decision

#8156 fix bad markdown causing link to not work
  docs/SlavaUkraini/download.md
Labels: bug, docs

#8143 Add redirect to wanted site
  docs/index.md
Labels: docs

#8144 Cover Rectangle with unit Tests
  spec/suites/layer/vector/RectangleSpec.js
Labels: tests

#8174 give the anchor attribute a data prefix in docs
  docs/SlavaUkraini/docs/js/reference.js
Labels: docs

#6685 Implemented missing logic for noMoveStart when using panTo function
  spec/suites/map/MapSpec.js
  src/map/Map.js
Labels: bug

#8090 Refactor / Extend VideoOverlay Tutorial (ImageOverlay, SVGOverlay)
  docs/SlavaUkraini/examples.md
  docs/SlavaUkraini/examples/overlays/example-image.md
  docs/SlavaUkraini/examples/overlays/example-nocontrols.md
  docs/SlavaUkraini/examples/overlays/example-svg.md
  docs/SlavaUkraini/examples/overlays/example-video.md
  docs/SlavaUkraini/examples/overlays/index.md
  docs/SlavaUkraini/examples/overlays/thumbnail.gif
  docs/SlavaUkraini/examples/video-overlay/example-bounds.md
  docs/SlavaUkraini/examples/video-overlay/index.md
Labels: docs

#8182 Add missing handler tests
  spec/index.html
  spec/suites/SpecHelper.js
  spec/suites/map/handler/Map.DoubleClickZoomSpec.js
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
Labels: tests

#8183 attribution flag now resizes with font-size changes
  dist/leaflet.css
  src/control/Control.Attribution.js
Labels: accessibility

#8195 Shorter Bundlemon check names
  package.json
Labels: workflow

#8198 Fix links in accessibility guide
  docs/examples/accessibility/index.md
Labels: bug, docs
