Repository Leaflet/Leaflet, pull requests merged in 2022-12, with the labels that each got.

#8711 Add leaflet-polar-graticule to plugins list
  docs/_plugins/synthetic-overlays/leaflet-polar-graticule.md
Labels: plugins

#8714 Adding badges to plugin page
  docs/_includes/plugin_category_table.html
  docs/plugins.md
Labels: docs, plugins

#8590 Added option for setting value of `aria-label` for popup close button
  spec/suites/layer/PopupSpec.js
  src/layer/Popup.js
Labels: accessibility

#8678 Rename 'closed' parameter of 'latLngsToCoords' to 'close' to avoid confusion
  src/layer/GeoJSON.js
Labels: api, docs

#8727 Replace `DomUtil.hasClass()` with `classList.contains()`
  spec/suites/dom/DomUtilSpec.js
  spec/suites/layer/ImageOverlaySpec.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  src/dom/DomUtil.js
  src/dom/Draggable.js
Labels: refactoring, breaking

#8728 Replace `DomUtil.getClass()` with `classList.value`
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
Labels: refactoring, breaking

#8729 Remove `DomUtil.setClass()` method
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
Labels: refactoring, api, breaking

#8731 Replace `DomUtil.addClass()` with `classList.add()`
  spec/suites/dom/DomUtilSpec.js
  src/control/Control.Layers.js
  src/control/Control.Zoom.js
  src/control/Control.js
  src/dom/DomUtil.js
  src/dom/Draggable.js
  src/layer/DivOverlay.js
  src/layer/ImageOverlay.js
  src/layer/Popup.js
  src/layer/SVGOverlay.js
  src/layer/Tooltip.js
  src/layer/VideoOverlay.js
  src/layer/marker/Marker.Drag.js
  src/layer/marker/Marker.js
  src/layer/tile/GridLayer.js
  src/layer/vector/Canvas.js
  src/layer/vector/Renderer.js
  src/layer/vector/SVG.js
  src/map/Map.js
  src/map/handler/Map.BoxZoom.js
  src/map/handler/Map.Drag.js
  src/map/handler/Map.TouchZoom.js
Labels: refactoring, api, breaking

#8730 Remove `DomUtil.setOpacity`
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
  src/layer/DivOverlay.js
  src/layer/ImageOverlay.js
  src/layer/Tooltip.js
  src/layer/marker/Marker.js
  src/layer/tile/GridLayer.js
Labels: refactoring, api, breaking

#8732 Replace `DomUtil.removeClass()` with `classList.remove()`
  spec/suites/dom/DomUtilSpec.js
  src/control/Control.Layers.js
  src/control/Control.Zoom.js
  src/dom/DomUtil.js
  src/dom/Draggable.js
  src/layer/DivOverlay.js
  src/layer/Popup.js
  src/layer/Tooltip.js
  src/layer/marker/Marker.Drag.js
  src/layer/vector/Canvas.js
  src/map/Map.js
  src/map/handler/Map.BoxZoom.js
  src/map/handler/Map.Drag.js
  src/map/handler/Map.TouchZoom.js
Labels: refactoring, api, breaking

#8733 Remove `DomUtil.TRANSFORM` constant
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
  src/map/Map.js
Labels: refactoring, api, breaking

#8734 Remove `TRANSITION` and `TRANSITION_END` constants from `DomUtil`
  src/dom/DomUtil.js
  src/map/Map.js
Labels: refactoring, api, breaking

#8735 Replace `DomUtil.remove()` with `Element.remove()`
  docs/examples/extending/extending-2-layers.md
  spec/suites/dom/DomUtilSpec.js
  spec/suites/map/MapSpec.js
  src/control/Control.js
  src/dom/DomUtil.js
  src/layer/DivOverlay.js
  src/layer/ImageOverlay.js
  src/layer/marker/Marker.js
  src/layer/tile/GridLayer.js
  src/layer/tile/TileLayer.js
  src/layer/vector/Canvas.js
  src/layer/vector/SVG.js
  src/map/Map.js
  src/map/handler/Map.BoxZoom.js
Labels: refactoring, api, breaking

#8736 Replace `DomUtil.empty()` with `Element.replaceChildren()`
  spec/suites/dom/DomUtilSpec.js
  src/control/Control.Layers.js
  src/dom/DomUtil.js
  src/layer/marker/DivIcon.js
Labels: refactoring, api, breaking

#8738 Remove vendor prefixes when setting `userSelect` style
  src/dom/DomUtil.js
Labels: refactoring, breaking

#8739 Remove `DomUtil.testProp()`
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
Labels: refactoring, api, breaking

#8742 Lock `actions/cache` to version 3.2.0
  .github/workflows/main.yml
Labels: bug, workflow

#8744 Run CI on latest version of Ubuntu
  .github/workflows/main.yml
Labels: workflow

#8741 Fix implementation for disabling & enabling text selection
  debug/tests/text-selection.html
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
Labels: bug, refactoring, compatibility, ios

#8743 Run CI on latest version of Windows
  .github/workflows/main.yml
Labels: workflow

#8747 Remove `DomUtil.getStyle()`
  spec/suites/dom/DomUtilSpec.js
  src/dom/DomUtil.js
  src/layer/Popup.js
  src/layer/marker/Icon.Default.js
  src/map/Map.js
Labels: refactoring, api, breaking

#8748 Remove `Browser.any3d`
  spec/suites/SpecHelper.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/map/MapSpec.js
  src/core/Browser.js
  src/dom/DomUtil.js
  src/layer/tile/GridLayer.js
  src/layer/vector/Renderer.js
  src/map/Map.js
Labels: refactoring, api, breaking

#8755 Remove SVG feature detection code
  src/control/Control.Attribution.js
  src/core/Browser.js
  src/layer/vector/SVG.js
Labels: refactoring, api, breaking

#8753 Remove `noConflict()`
  build/docs-misc.leafdoc
  build/leafdoc-templates/html.hbs
  spec/index.html
  spec/suites/core/GeneralSpec.js
  src/LeafletWithGlobals.js
Labels: refactoring, api, breaking

#8751 Remove browser specific detection code for CSS transforms
  src/core/Browser.js
Labels: refactoring, api, breaking

#8750 Use OS name as part of cache key for jobs
  .github/workflows/main.yml
Labels: bug, workflow

#8749 Hold element positions in WeakMap
  docs/examples/extending/pixelorigin.md
  spec/suites/layer/PopupSpec.js
  src/dom/DomUtil.js
Labels: refactoring

#8752 Remove `L_NO_TOUCH` global switch
  build/docs-misc.leafdoc
  src/core/Browser.js
Labels: refactoring, api, breaking

#8754 Remove `Browser.canvas` feature detection
  spec/suites/map/MapSpec.js
  src/core/Browser.js
  src/layer/vector/Canvas.js
Labels: refactoring, api, breaking

#8769 Remove Windows platform detection
  src/core/Browser.js
Labels: refactoring, api, breaking
