Repository Leaflet/Leaflet, pull requests merged in 2022-05, with the labels that each got.

#8207 Prevent major updates of Mocha through Dependabot
  .github/dependabot.yml
Labels: dependencies, workflow, ie

#8211 Update CSS `color-adjust` to `print-color-adjust`
  dist/leaflet.css
Labels: compatibility

#8212 Add pre-commit hook to fix linting issues
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: workflow

#8229 A couple of site SEO fixes
  docs/_layouts/dialog_frame.html
  docs/reference-versions.html
Labels: docs

#8230 Correct heading level in GeoJSON tutorial
  docs/examples/geojson/index.md
Labels: bug, docs

#8227 DomEvent.DoubleTap ignores clicks on <label>s
  spec/suites/dom/DomEvent.DoubleTapSpec.js
  src/dom/DomEvent.DoubleTap.js
  src/dom/DomEvent.js
Labels: bug, compatibility

#8246 Configure YAML issues forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/improve_documentation.yml
  .github/ISSUE_TEMPLATE/support.md
Labels: workflow

#8247 Tooltip accessibility improvements: focus and voice over
  spec/suites/layer/TooltipSpec.js
  src/layer/Tooltip.js
Labels: accessibility

#7386 Better PosAnimation example
  src/dom/PosAnimation.js
Labels: bug, docs

#8260 Remove border styles in overflowing popups
  dist/leaflet.css
  src/layer/Popup.js
Labels: ux, needs decision

#7818 Replace Mapbox with OpenStreetMap
  debug/map/svgoverlay.html
  debug/map/videooverlay.html
  debug/vector/moving-canvas.html
  docs/examples.md
  docs/examples/accessibility/example.md
  docs/examples/choropleth/example-basic.md
  docs/examples/choropleth/example-color.md
  docs/examples/choropleth/example.md
  docs/examples/choropleth/index.md
  docs/examples/extending/tilt.md
  docs/examples/extending/watermark.md
  docs/examples/geojson/example.md
  docs/examples/geojson/geojson-example.html
  docs/examples/geojson/geojson.html
  docs/examples/layers-control/example.md
  docs/examples/layers-control/index.md
  docs/examples/mobile/example.md
  docs/examples/mobile/index.md
  docs/examples/overlays/example-image.md
  docs/examples/overlays/example-nocontrols.md
  docs/examples/overlays/example-svg.md
  docs/examples/overlays/example-video.md
  docs/examples/overlays/index.md
  docs/examples/quick-start/example-basic.md
  docs/examples/quick-start/example-overlays.md
  docs/examples/quick-start/example.md
  docs/examples/quick-start/index.md
  src/control/Control.Attribution.js
Labels: docs, needs decision
