Repository Leaflet/Leaflet, pull requests merged in 2023-05, with the labels that each got.

#8945 Plugins: add Leaflet.MeasurePolygon
  docs/_plugins/measurement/leaflet-measure-polygon.md
Labels: plugins

#8952 Replace expect.js with Chai
  .github/workflows/main.yml
  package-lock.json
  package.json
  spec/.eslintrc.js
  spec/karma.conf.js
  spec/suites/SpecHelper.js
  spec/suites/control/Control.LayersSpec.js
  spec/suites/control/ControlSpec.js
  spec/suites/core/ClassSpec.js
  spec/suites/core/EventsSpec.js
  spec/suites/core/UtilSpec.js
  spec/suites/dom/DomEvent.DoubleTapSpec.js
  spec/suites/dom/DomEvent.PointerSpec.js
  spec/suites/dom/DomEventSpec.js
  spec/suites/dom/DomUtilSpec.js
  spec/suites/geo/LatLngBoundsSpec.js
  spec/suites/geo/LatLngSpec.js
  spec/suites/geo/crs/CRSSpec.js
  spec/suites/geometry/BoundsSpec.js
  spec/suites/geometry/LineUtilSpec.js
  spec/suites/geometry/PointSpec.js
  spec/suites/geometry/PolyUtilSpec.js
  spec/suites/layer/FeatureGroupSpec.js
  spec/suites/layer/GeoJSONSpec.js
  spec/suites/layer/ImageOverlaySpec.js
  spec/suites/layer/LayerGroupSpec.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  spec/suites/layer/VideoOverlaySpec.js
  spec/suites/layer/marker/Icon.DefaultSpec.js
  spec/suites/layer/marker/Marker.DragSpec.js
  spec/suites/layer/marker/MarkerSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/layer/vector/CanvasSpec.js
  spec/suites/layer/vector/CircleMarkerSpec.js
  spec/suites/layer/vector/CircleSpec.js
  spec/suites/layer/vector/PathSpec.js
  spec/suites/layer/vector/PolygonSpec.js
  spec/suites/layer/vector/PolylineSpec.js
  spec/suites/layer/vector/RectangleSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.BoxZoom.js
  spec/suites/map/handler/Map.DragSpec.js
  spec/suites/map/handler/Map.KeyboardSpec.js
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
  spec/suites/map/handler/Map.TapHoldSpec.js
  spec/suites/map/handler/Map.TouchZoomSpec.js
  src/map/Map.js
Labels: refactoring, tests, workflow

#8910 Prevent adding layer while expanding Layer-Control on mobile
  src/control/Control.Layers.js
Labels: blocker

#8890 Fix tooltip focus listener if getElement is no function
  spec/suites/layer/TooltipSpec.js
  src/layer/Tooltip.js
Labels: blocker

#8672 Fix issue whereby tooltips loaded dynamically while moving the map were never shown.
  spec/suites/layer/TooltipSpec.js
  src/dom/Draggable.js
  src/layer/Tooltip.js
Labels: bug
