Repository Leaflet/Leaflet, pull requests merged in 2023-02, with the labels that each got.

#8823 Destructure `statics` and `includes` from class properties
  src/core/Class.js
Labels: refactoring

#8829 Remove jitter debug page
  debug/hacks/jitter.html
Labels: refactoring

#8831 Provide file extensions when running ESLint
  build/rollup-config.mjs
  package.json
Labels: workflow

#8832 Convert control layers debug page to ESM
  debug/map/control-layers.html
Labels: refactoring

#8830 Convert canvas debug page to ESM
  debug/map/canvas.html
Labels: refactoring

#8835 Convert geolocation debug page to ESM
  debug/map/geolocation.html
Labels: refactoring

#8834 Convert controls debug page to ESM
  debug/map/controls.html
Labels: refactoring

#8838 Convert map debug pages to ESM
  debug/map/grid.html
  debug/map/iframe-map.html
  debug/map/iframe.html
  debug/map/image-overlay.html
  debug/map/layer-remove-add.html
  debug/map/layer_remove_add.html
  debug/map/map-mobile.html
  debug/map/map-popup.html
  debug/map/map-scaled.html
  debug/map/map.html
  debug/map/marker-autopan.html
  debug/map/markers.html
  debug/map/max-bounds-bouncy.html
  debug/map/max-bounds-infinite.html
  debug/map/max-bounds.html
  debug/map/opacity.html
  debug/map/popup-keep-in-view.html
  debug/map/popup-keepinview.html
  debug/map/popup.html
  debug/map/rollup.html
  debug/map/scroll.html
  debug/map/simple-proj.html
  debug/map/svg-overlay.html
  debug/map/svgoverlay.html
  debug/map/tile-debug.html
  debug/map/tile-opacity.html
  debug/map/tile.html
  debug/map/tooltip.html
  debug/map/video-overlay.html
  debug/map/videooverlay.html
  debug/map/wms-marble.html
  debug/map/wms.html
  debug/map/zoom-delta.html
  debug/map/zoom-levels.html
  debug/map/zoom-pan.html
  debug/map/zoom-remain-centered.html
  debug/map/zoomlevels.html
  debug/map/zoompan.html
Labels: refactoring

#8844 Always build ESM version in watch mode
  build/rollup-config.mjs
Labels: workflow

#8825 Move `callInitHooks()` to prototype of `Class`
  src/core/Class.js
Labels: refactoring

#8824 Use `Object.setPrototypeOf()` to extend `Class`
  src/core/Class.js
Labels: refactoring

#8637 Added two more test cases for the unproject map method
  spec/suites/map/MapSpec.js
Labels: tests

#8632 Revamp synthetic dblclick event instantiation
  spec/suites/dom/DomEvent.DoubleTapSpec.js
  src/dom/DomEvent.DoubleTap.js
Labels: refactoring

#8758 Use Pointer Events for `Map.Keyboard`
  src/map/handler/Map.Keyboard.js
Labels: refactoring

#8871 Convert `Class` to a JavaScript `class`
  src/core/Class.js
Labels: refactoring

#8784 Fix rounding errors in center calculation for small layers
  spec/suites/geometry/LineUtilSpec.js
  spec/suites/geometry/PolyUtilSpec.js
  src/geometry/LineUtil.js
  src/geometry/PolyUtil.js
Labels: blocker, bug

#8611 Implement BlanketOverlay as Renderer superclass
  build/docs-index.leafdoc
  build/leafdoc-templates/html.hbs
  debug/vector/blanket.html
  src/layer/BlanketOverlay.js
  src/layer/index.js
  src/layer/vector/Canvas.js
  src/layer/vector/Renderer.js
  src/layer/vector/SVG.js
Labels: feature, refactoring
