Repository Leaflet/Leaflet, pull requests merged in 2023-01, with the labels that each got.

#8770 Remove Gecko-based browser detection
  src/core/Browser.js
Labels: refactoring, api, breaking

#8771 Remove references to PhantomJS
  spec/suites/layer/ImageOverlaySpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.TapHoldSpec.js
Labels: refactoring

#8772 Remove passive event detection
  src/core/Browser.js
  src/dom/DomEvent.js
Labels: refactoring, api, breaking

#8768 Add shadow-icon as svg icon and add white circle to marker-icon
  src/images/marker-shadow.svg
  src/images/marker.svg
Labels: refactoring

#8773 Remove WebKit-based browser detection
  src/core/Browser.js
Labels: refactoring, api, breaking

#8760 Refactor Event handling and happen.js
  package-lock.json
  package.json
  spec/.eslintrc.js
  spec/index.html
  spec/karma.conf.js
  spec/suites/SpecHelper.js
  spec/suites/control/Control.LayersSpec.js
  spec/suites/dom/DomEvent.DoubleTapSpec.js
  spec/suites/dom/DomEvent.PointerSpec.js
  spec/suites/dom/DomEventSpec.js
  spec/suites/dom/DomUtilSpec.js
  spec/suites/layer/PopupSpec.js
  spec/suites/layer/TooltipSpec.js
  spec/suites/layer/marker/MarkerSpec.js
  spec/suites/layer/vector/CanvasSpec.js
  spec/suites/layer/vector/PathSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.BoxZoom.js
  spec/suites/map/handler/Map.DoubleClickZoomSpec.js
  spec/suites/map/handler/Map.DragSpec.js
  spec/suites/map/handler/Map.KeyboardSpec.js
  spec/suites/map/handler/Map.ScrollWheelZoomSpec.js
  spec/suites/map/handler/Map.TapHoldSpec.js
  src/control/Control.Layers.js
  src/layer/Popup.js
  src/map/handler/Map.BoxZoom.js
  src/map/handler/Map.Keyboard.js
Labels: refactoring

#8644 Vector Drift Test Pinch Zoom Fix
  spec/suites/map/handler/Map.TouchZoomSpec.js
Labels: tests

#8796 Remove deprecated `which` and change `button` to main-button
  spec/suites/map/handler/Map.TouchZoomSpec.js
  src/dom/Draggable.js
  src/map/handler/Map.BoxZoom.js
Labels: refactoring

#8800 Drop `__super__` property from Class
  src/core/Class.js
Labels: refactoring, breaking
