Repository Leaflet/Leaflet, pull requests merged in 2025-03, with the labels that each got.

#9303 add test for project method
  spec/suites/map/MapSpec.js
Labels: tests

#9005 Bugfix: refocus map after using layers control (#9004)
  spec/suites/control/Control.LayersSpec.js
  src/control/Control.Layers.js
  src/control/Control.js
Labels: bug

#8613 GridLayer construct url with integer {z} for fractional zoom
  spec/suites/layer/tile/TileLayerSpec.js
  src/layer/tile/TileLayer.js
Labels: bug

#8455 Update browser support list
  docs/index.html
Labels: docs, later

#9048 Clean up DOM event listeners when destroying Map's animation proxy
  src/map/Map.js
Labels: bug, performance

#8810 Replace animation frame polyfill with native API
  spec/suites/core/UtilSpec.js
  spec/suites/dom/DomEvent.DoubleTapSpec.js
  spec/suites/layer/tile/GridLayerSpec.js
  spec/suites/layer/tile/TileLayerSpec.js
  spec/suites/layer/vector/CanvasSpec.js
  spec/suites/map/MapSpec.js
  spec/suites/map/handler/Map.TapHoldSpec.js
  src/core/Util.js
  src/dom/PosAnimation.js
  src/layer/marker/Marker.Drag.js
  src/layer/tile/GridLayer.js
  src/layer/vector/Canvas.js
  src/map/Map.js
  src/map/handler/Map.Drag.js
  src/map/handler/Map.TouchZoom.js
Labels: refactoring, api, compatibility, breaking
